apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vanilla-uploads
  namespace: vanilla-forums
  labels:
    app: vanilla-forums
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs-standard
  resources:
    requests:
      storage: 20Gi
