apiVersion: v1
kind: Service
metadata:
  name: vanilla-forums
  namespace: vanilla-forums
  labels:
    app: vanilla-forums
spec:
  type: ClusterIP
  selector:
    app: vanilla-forums
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
