apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vanilla-forums
  namespace: vanilla-forums
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns01"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - vanilla.lab.hq.solidrust.net
    secretName: vanilla-forums-tls
  rules:
  - host: vanilla.lab.hq.solidrust.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vanilla-forums
            port:
              number: 80
